### ISSUE TITLE
Bug: overlay not working

### ISSUE THREAD

**Issue by t-divya** [RichmondCroft/dyslens#38]
## Steps to reproduce
1. Open the extension panel and enable the overlay
2. Disable the overlay
3. Enable the overlay
4. The overlay does not appear back

## Expected Behaviour
The overlay should be displayed every time the option is enabled

**Comment by digvijayu** [comment]
Fixed with the following PR
https://github.com/RichmondCroft/dyslens/pull/39

**Comment by digvijayu** [comment]
merged..
