### ISSUE TITLE
Bug: Overlay settings are not enabled when extension is installed for the first time

### ISSUE THREAD

**Issue by t-divya** [RichmondCroft/dyslens#41]
## Description:

Currently overlay settings are not enabled by default  once extension is installed. 

## Steps to Replicate:

1. Open chrome extension go to overlay settings.
2. Settings are disabled by default, enable the button.
3. Select any color, the overlay with that color should appear in the website but it is not displayed.
4. Now refresh the current page, your overlay with chosen color will appear now.

## Expected Behaviour:

The overlay settings should be enabled once extension is installed and by default the overlay should be visible to the user.

**Comment by digvijayu** [comment]
not reproducable
